#! /user/bin/bash

#automating the creation of new users on linux server

#setting name of csv_file
CSV_FILE=names.csv

GROUP_NAME=developers

#setting name of ssh directory for skel
SSH_SKEL=/etc/skel/.ssh

#variable for public key file 



#Check if group exists
if [$(getent group developers)];
then
    echo group already exists
else
    sudo groupadd $GROUP_NAME
    echo group successfully created
fi 

#add ssh folder to skel directory
if [-d "SSH_SKEL"];
then 
    echo "SSH_SKEL already exists"
else 
    sudo mkdir -p SSH_SKEL

#create each user on the server
while IFS= read USERNAME
    do 
        #Check if the user already exists
        if [$(getent passwd $USERNAME)];
        then 
            echo $USERNAME alread exists
        else 
            sudo useradd -m -G $GROUP_NAME $USERNAME 
